# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: >
  <p><i>Hands-On</i> Pembelajaran Mesin untuk Inversi Geofisika</p>
author: >
  <a href="mailto:mheriyanto37@gmail.com">M. Heriyanto</a>,
  <a href="https://ezygeo.github.io">ezygeo</a>, Jakarta, Indonesia. <a href="https://choosealicense.com/licenses/mit">MIT License</a>.
copyright: '2016–2022'
logo: figures/logos/ezygeo.png

exclude_patterns:
  - __pycache__
  - .github
  - README.md
  - sources

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # execute_notebooks: force
  execute_notebooks: off

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: figures/images/favicon.ico
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  extra_navbar: >
    <b>partially published on:</b></br>
    <a href="https://medium.com/@mheriyanto"><img src="https://raw.githubusercontent.com/mheriyanto/mheriyanto/master/icons/medium.png" height="30" width="30" title="medium"></a>
    <a href="https://dev.to/mheriyanto"><img src="https://raw.githubusercontent.com/mheriyanto/mheriyanto/master/icons/dev.png" height="30" width="30" title="dev.to"></a>
    </br></br>
    <b>authors:</b></br>
    <a href="https://mheriyanto.dev"><img src="https://raw.githubusercontent.com/mheriyanto/mheriyanto.github.io/master/assets/images/mh-logo.png" height="45" width="45" title="mheriyanto"></a>
    <a href="https://ezygeo.github.io"><img src="https://raw.githubusercontent.com/mheriyanto/mheriyanto.github.io/master/assets/logos/ezygeo.png" height="45" width="45" title="ezygeo"></a>
    </br></br>
    <a href="https://doi.org/10.5281/zenodo.1807591"><img src="https://zenodo.org/badge/DOI/10.5281/zenodo.1807591.svg" alt="DOI"></a></br>
    <a href="https://github.com/ezygeo-ai/mlgi/blob/master/LICENSE"><img src="https://img.shields.io/github/license/ezygeo-ai/mlgi.svg" alt="Licence"></a>
    </br>
    <a href="https://www.hitwebcounter.com" target="_blank"><img src="https://hitwebcounter.com/counter/counter.php?page=8045874&style=0006&nbdigits=5&type=page&initCount=0" title="visitor" Alt="web-counter" border="0"/></a> 
  # extra_footer: >
  #   <p>
  #   This work is licenced under the <a href="https://choosealicense.com/licenses/mit">MIT License</a>.
  #   </p>
  home_page_in_navbar: true
  # baseurl: ""
  announcement: "News: buku berbasis web ini sedang dalam tahap development." # A banner announcement at the top of the site.

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: false
  latex_documents:
    targetname: docs/ml_inv_geo.tex

# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "https://colab.research.google.com/drive/1QVn2yRf02UQKvKZrbBWFN2PMlNIdVasR?usp=sharing" # The URL of Google Colab (https://colab.research.google.com)

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - data/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ezygeo-ai/mlgi  # Online location of your book
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

sphinx:
  config:
    bibtex_reference_style: author_year