# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: >
  <p><i>Hands-On</i> Pembelajaran Mesin untuk Inversi Geofisika</p>
author: >
  <a href="mailto:mheriyanto37@gmail.com">M. Heriyanto</a>,
  <a href="https://ezygeo.github.io">ezygeo</a>, Jakarta, Indonesia
copyright: '2016–2022'
logo: figures/logos/ezygeo.png

exclude_patterns:
  - __pycache__
  - .github
  - README.md
  - sources

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # execute_notebooks: force
  execute_notebooks: off

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: figures/images/favicon.ico
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  extra_navbar: >
    <a href="https://mheriyanto.dev"><img src="https://raw.githubusercontent.com/mheriyanto/mheriyanto.github.io/master/assets/images/mh-logo.png" height="45" width="45" title="mheriyanto"></a>
    <a href="https://ezygeo.github.io"><img src="https://raw.githubusercontent.com/mheriyanto/mheriyanto.github.io/master/assets/logos/ezygeo.png" height="45" width="45" title="ezygeo"></a>
    </br>
    </br>
    <a href="https://doi.org/10.5281/zenodo.1807591"><img src="https://zenodo.org/badge/DOI/10.5281/zenodo.1807591.svg" alt="DOI"></a></br>
    <a href="https://github.com/ezygeo-ai/mlgi/blob/master/LICENSE"><img src="https://img.shields.io/github/license/ezygeo-ai/mlgi.svg" alt="Licence"></a>
  extra_footer: >
    <p>
    This work is licenced under the <a href="https://choosealicense.com/licenses/mit">MIT License</a>.
    </p>
  home_page_in_navbar: true

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true
  latex_documents:
    targetname: docs/ml_inv_geo.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - data/references.bib

sphinx:
  config:
    bibtex_reference_style: author_year

# Information about where the book exists on the web
repository:
  url: https://github.com/ezygeo-ai/mlgi  # Online location of your book
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)